### ISSUE TITLE
unicodedecode error rendering richtexttile

### ISSUE THREAD

**Issue by djay** [plone/plone.app.standardtiles#111]
```
2021-02-04 01:17:18,944 - plone.subrequest - ERROR - Error handling subrequest to http://localhost:63339/plone/testdoc/@@plone.app.standardtiles.field?field=IRichText-text&X-Tile-Persistent=yes
Traceback (most recent call last):
  File "/Users/dylanjay/Projects/download-cache/eggs/plone.subrequest-1.8.7-py2.7.egg/plone/subrequest/__init__.py", line 155, in subrequest
    bind=1
  File "/Users/dylanjay/Projects/download-cache/eggs/Zope2-2.13.30-py2.7.egg/ZPublisher/mapply.py", line 78, in mapply
    else: return object(*args)
  File "/Users/dylanjay/Projects/download-cache/eggs/plone.app.standardtiles-2.3.2-py2.7.egg/plone/app/standardtiles/field.py", line 123, in __call__
    return self._wrap_widget(widget.render())
  File "/Users/dylanjay/Projects/download-cache/eggs/plone.app.standardtiles-2.3.2-py2.7.egg/plone/app/standardtiles/field.py", line 96, in _wrap_widget
    if render.rstrip().endswith(u'</html>'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7: ordinal not in range(128)
```

Shown in this test https://github.com/collective/collective.collectionfilter/runs/1824792008?check_suite_focus=true

**Comment by djay** [comment]
The bug is here https://github.com/plone/plone.app.standardtiles/issues/111

in previous versions this code was which handled if the render was not unicode?

```
    def _wrap_widget(self, render):
        print(type(render))
        if unicode(render).rstrip().endswith(u'</html>'):
            return render
```

**Comment by djay** [comment]
Seems this was fixed by https://github.com/collective/collective.collectionfilter/pull/133/commits/eefcb8ac389caf87cb85204a381cf84919329767.
Not sure why this breaks tiles but not other schema forms so it's still perhaps a bug.
