### ISSUE TITLE
Error when rendering footer portlet

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.standardtiles#51]
Using site layouts the footer portlet does not render.
```
2016-12-09 16:14:34 ERROR plone.subrequest Error handling subrequest to http://localhost:8080/Plone/@@plone.app.standardtiles.portletmanager/footer-portlets?manager=plone.footerportlets
Traceback (most recent call last):
  File "/home/jensens/.buildout/shared-eggs/plone.subrequest-1.8-py2.7.egg/plone/subrequest/__init__.py", line 154, in subrequest
    bind=1
  File "/home/jensens/.buildout/shared-eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/mapply.py", line 78, in mapply
    else: return object(*args)
  File "/home/workspacejensens/buildout-nwf/srcaddons/plone.app.standardtiles/plone/app/standardtiles/portlets/portletmanager.py", line 40, in __call__
    view = findView(self, viewName)
  File "/home/workspacejensens/buildout-nwf/srcaddons/plone.app.standardtiles/plone/app/standardtiles/portlets/utils.py", line 37, in findView
    layoutPolicy.mark_view(view)
  File "/home/workspacejensens/buildout-nwf/srccore/plone.app.layout/plone/app/layout/globals/layout.py", line 42, in mark_view
    if context_state.is_view_template() and not IViewView.providedBy(view):
  File "/home/jensens/.buildout/shared-eggs/plone.memoize-1.2.0-py2.7.egg/plone/memoize/view.py", line 47, in memogetter
    value = cache[key] = func(*args, **kwargs)
  File "/home/workspacejensens/buildout-nwf/srccore/plone.app.layout/plone/app/layout/globals/context.py", line 105, in is_view_template
    current_url = self.current_base_url()
  File "/home/jensens/.buildout/shared-eggs/plone.memoize-1.2.0-py2.7.egg/plone/memoize/view.py", line 47, in memogetter
    value = cache[key] = func(*args, **kwargs)
  File "/home/workspacejensens/buildout-nwf/srccore/plone.app.layout/plone/app/layout/globals/context.py", line 48, in current_base_url
    self.context.absolute_url()
AttributeError: 'PortletManagerTile' object has no attribute 'absolute_url'

```

**Comment by datakurre** [comment]
Are you already working on this or just reporting for record? I should be able to look this very soon.

**Comment by jensens** [comment]
Just found it. I do not plan to use portlets in this project at all. So if you could look into it that would be great!
